# Generated by Django 5.0.1 on 2024-01-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('man', 'Manager'), ('hum', 'Human Resource'), ('cou', 'Counter'), ('pub', 'Officer public relations'), ('rom', 'Room attendant')], default='-----', max_length=30, null=True),
        ),
    ]
