# Generated by Django 5.0.1 on 2024-01-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='-----', help_text='Choose Gender', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('man', 'Manager'), ('hum', 'Human Resource'), ('cou', 'Counter'), ('pub', 'Officer public relations'), ('rom', 'Room attendant')], default='-----', help_text='Choose User Position in the hotel management', max_length=30, null=True),
        ),
    ]
