# Generated by Django 5.0.1 on 2024-01-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_user_gender_remove_user_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuserprofile',
            old_name='second_name',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='baseuserprofile',
            old_name='first_name',
            new_name='surnamename',
        ),
        migrations.AddField(
            model_name='baseuserprofile',
            name='age',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuserprofile',
            name='date_of_birth',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuserprofile',
            name='emergency_contact',
            field=models.CharField(default=None, help_text='Contact to your next of kin', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='-----', help_text='Choose Gender', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='baseuserprofile',
            name='given_name',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuserprofile',
            name='location',
            field=models.TextField(default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuserprofile',
            name='next_of_kin',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuserprofile',
            name='nin',
            field=models.CharField(blank=True, help_text='National Identification number', max_length=24, null=True, verbose_name='NIN'),
        ),
        migrations.AddField(
            model_name='baseuserprofile',
            name='place_of_birth',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('man', 'Manager'), ('hum', 'Human Resource'), ('cou', 'Counter'), ('pub', 'Officer public relations'), ('rom', 'Room attendant')], default='-----', help_text='Choose User Position in the hotel management', max_length=30, null=True),
        ),
    ]
