# Generated by Django 5.0.1 on 2024-01-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_rename_second_name_baseuserprofile_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuserprofile',
            old_name='surnamename',
            new_name='surname',
        ),
    ]
