# Generated by Django 5.0.1 on 2024-01-28 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_customgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(choices=[('ft', 'full-time'), ('pt', 'part-time'), ('ct', 'contract')], default='-----', help_text='Choose Status', max_length=15)),
                ('employment_start_date', models.DateField()),
                ('head_of_department', models.ForeignKey(help_text='Choose Department Head', limit_choices_to={'customgroup__leader__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head_positions', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
