# Generated by Django 5.0.1 on 2024-01-28 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_employmentinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentinformation',
            name='head_of_department',
            field=models.ForeignKey(help_text='Choose Department Head', limit_choices_to={'leading_groups__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head_positions', to=settings.AUTH_USER_MODEL),
        ),
    ]
