# Generated by Django 5.0.1 on 2024-01-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_employmentinformation_head_of_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinformation',
            name='department',
            field=models.CharField(choices=[('AD', 'administration'), ('bk', 'booking'), ('act', 'accounts'), ('ctn', 'canteen'), ('cng', 'cleaning')], default='-----', help_text='Choose Department', max_length=15),
        ),
    ]
