# Generated by Django 5.0.1 on 2024-01-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentinformation',
            name='head_of_department',
        ),
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
