# Generated by Django 5.0.1 on 2024-01-29 07:00

import django.core.validators
import django.db.models.deletion
import management.custom_validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_employmentinformation_head_of_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuserprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='-----', help_text='Choose Gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='baseuserprofile',
            name='nin',
            field=models.CharField(default=None, help_text='National Identification number', max_length=24, validators=[management.custom_validators.validate_nin], verbose_name='NIN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employmentinformation',
            name='head_of_department',
            field=models.ForeignKey(blank=True, help_text='Choose Department Head', limit_choices_to={'department_leader__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head_positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid email address')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('man', 'Manager'), ('hum', 'Human Resource'), ('cou', 'Counter'), ('pub', 'Officer public relations'), ('rom', 'Room attendant')], default='-----', help_text='Choose User Position in the hotel management', max_length=30),
        ),
    ]
