# Generated by Django 5.0.1 on 2024-01-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_baseuserprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuserprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
