# Generated by Django 5.0.1 on 2024-01-29 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_baseuserprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(blank=True, help_text='Input only the UGX amount e.g: 50000', max_length=17, null=True)),
                ('payment', models.CharField(blank=True, help_text='If applicable, provide bank account/airtel pay code/MOMO pay code.', max_length=15, null=True, verbose_name='Payment Details')),
                ('userid', models.CharField(help_text='Enter user ID number(01-99).', max_length=2, verbose_name='Personal ID')),
                ('ackno', models.BooleanField(default=False, help_text='Ask user if they consent to company policies and procedures.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='miscella', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
