# Generated by Django 5.0.1 on 2024-01-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_miscellaneous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscellaneous',
            name='ackno',
            field=models.BooleanField(default=False, help_text='Ask user if they consent to company policies and procedures.', verbose_name='Acknowledgement of company rules and procedures.'),
        ),
    ]
