# Generated by Django 5.0.1 on 2024-01-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_equipment_equipmentallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='total_number',
            field=models.IntegerField(default=0),
        ),
    ]
