# Generated by Django 5.0.1 on 2024-01-29 16:21

import management.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_equipment_total_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuserprofile',
            name='contact',
            field=models.CharField(max_length=10, validators=[management.custom_validators.validate_contact]),
        ),
        migrations.AlterField(
            model_name='baseuserprofile',
            name='emergency_contact',
            field=models.CharField(help_text='Contact to your next of kin', max_length=10, validators=[management.custom_validators.validate_contact]),
        ),
    ]
