# Generated by Django 5.0.1 on 2024-02-02 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_baseuserprofile_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuserprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', help_text='Choose Gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='employmentinformation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.departments'),
        ),
        migrations.AlterField(
            model_name='employmentinformation',
            name='employment_status',
            field=models.CharField(choices=[('ft', 'full-time'), ('pt', 'part-time'), ('ct', 'contract')], default='ft', help_text='Choose Status', max_length=15),
        ),
    ]
