# Generated by Django 5.0.1 on 2024-02-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_alter_baseuserprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('man', 'Manager'), ('hum', 'Human Resource'), ('cou', 'Counter'), ('pub', 'Officer public relations'), ('rom', 'Room attendant')], default='man', help_text='Choose User Position in the hotel management', max_length=30),
        ),
    ]
