# Generated by Django 4.2 on 2024-02-16 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='time_of_allocation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='equipmentallocation',
            name='time_of_allocation',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
