# Generated by Django 4.2 on 2024-02-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_equipment_time_of_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneous',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'MoMo Pay'), ('airtel', 'Airtel Money Pay'), ('bank', 'Bank Transfer')], default='momo', help_text='Choose Payment Method', max_length=20),
        ),
    ]
