# Generated by Django 4.2 on 2024-02-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_miscellaneous_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinformation',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
