# Generated by Django 4.2 on 2024-02-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_employmentinformation_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentinformation',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
    ]
