# Generated by Django 4.2 on 2024-02-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_remove_employmentinformation_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='Enter User Position in the hotel management', max_length=30, null=True),
        ),
    ]
