# Generated by Django 4.2 on 2024-02-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='ocument',
            new_name='document',
        ),
    ]
