# Generated by Django 4.2 on 2024-02-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_rename_ocument_document_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
