# Generated by Django 4.2 on 2024-02-26 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_employpaymentmethod_menuanddrinkschoice_and_more'),
        ('management', '0033_alter_document_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentinformation',
            name='employment_status',
            field=models.ForeignKey(blank=True, default='----', null=True, on_delete=django.db.models.deletion.CASCADE, to='choices.employmentstatus'),
        ),
    ]
