# Generated by Django 4.2 on 2024-02-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_employpaymentmethod_menuanddrinkschoice_and_more'),
        ('management', '0034_alter_employmentinformation_employment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AddField(
            model_name='baseuserprofile',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Choose User Position in the hotel management', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='choices.positions'),
        ),
        migrations.AlterField(
            model_name='baseuserprofile',
            name='gender',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='choices.genderchoices'),
        ),
        migrations.AlterField(
            model_name='employmentinformation',
            name='employment_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='choices.employmentstatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='payment',
            field=models.CharField(blank=True, help_text='Provide Payment Info according to payment method above.', max_length=15, null=True, verbose_name='Payment Information'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='payment_method',
            field=models.ForeignKey(help_text='Choose Payment Method', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='choices.employpaymentmethod'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='userid',
            field=models.CharField(help_text='Enter user ID like (01-99 or R-56).', max_length=4, verbose_name='Personal ID'),
        ),
    ]
