# Generated by Django 4.2 on 2024-03-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0006_delete_reservationstatus'),
        ('management', '0035_remove_user_position_baseuserprofile_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuserprofile',
            name='gender',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='gender_c', to='choices.genderchoices'),
        ),
        migrations.AlterField(
            model_name='baseuserprofile',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Choose User Position in the hotel management', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_position', to='choices.positions'),
        ),
    ]
