# Generated by Django 4.2 on 2024-03-09 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_alter_baseuserprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
