# Generated by Django 4.2 on 2024-02-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_miscellaneous_paymentmethod_delete_mychoice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Miscellaneous',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
