# Generated by Django 5.0.1 on 2024-02-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='total_in_store',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='units',
            field=models.CharField(blank=True, help_text='E.g Kgs, meters, pieces', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='available_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity_on_hand',
            field=models.DecimalField(decimal_places=2, help_text='Total number of this Item Received.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity',
            field=models.IntegerField(help_text="If 'reception', quantity should be postive. If 'Consumption' or 'Transfer', quantity should be negative."),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
