# Generated by Django 5.0.1 on 2024-02-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventoryitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Number of Items already found in the store.', max_digits=10),
        ),
    ]
