# Generated by Django 5.0.1 on 2024-02-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('consumption', 'Consumption'), ('transfer', 'Transfer')], max_length=15),
        ),
    ]
