# Generated by Django 5.0.1 on 2024-02-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorytransaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
