# Generated by Django 5.0.1 on 2024-02-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchaseorderitem_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity_on_hand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total number of this Item Received.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='total_in_store',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='available_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
