# Generated by Django 5.0.1 on 2024-02-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryitem_quantity_on_hand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'verbose_name': 'Item Transaction', 'verbose_name_plural': 'Item Transactions'},
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='available_quantity',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='initial_total_in_store',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
