# Generated by Django 5.0.1 on 2024-02-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='current_quantity',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
