# Generated by Django 5.0.1 on 2024-02-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventorytransaction_current_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorytransaction',
            old_name='current_quantity',
            new_name='remaining_in_store',
        ),
    ]
