# Generated by Django 5.0.1 on 2024-02-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_current_quantity_inventorytransaction_remaining_in_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
    ]
