# Generated by Django 4.2 on 2024-02-16 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_purchaseorderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
