# Generated by Django 4.2 on 2024-02-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventoryitem_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
