# Generated by Django 4.2 on 2024-02-24 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventoryitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
