# Generated by Django 4.2 on 2024-02-27 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('choices', '0003_servicechoices_and_more'),
        ('hotel', '0043_alter_booking_booking_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GuestRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrDrinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sub_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_or_drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.menuanddrinkschoice')),
                ('guest_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_and_drinks', to='restaurant.guestroom')),
            ],
        ),
    ]
