# Generated by Django 4.2 on 2024-02-27 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0043_alter_booking_booking_source_and_more'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodordrinks',
            name='guest_room',
        ),
        migrations.AddField(
            model_name='foodordrinks',
            name='booking_guest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reserving_food', to='hotel.booking'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GuestRoom',
        ),
    ]
