# Generated by Django 4.2 on 2024-02-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0043_alter_booking_booking_source_and_more'),
        ('restaurant', '0002_remove_foodordrinks_guest_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodordrinks',
            name='reserving_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserving_food', to='hotel.reservation'),
        ),
        migrations.AlterField(
            model_name='foodordrinks',
            name='booking_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_food', to='hotel.booking'),
        ),
    ]
