# Generated by Django 4.2 on 2024-02-29 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0004_alter_servicechoices_options_and_more'),
        ('restaurant', '0003_foodordrinks_reserving_guest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=25)),
                ('mobile_contact', models.CharField(max_length=25)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_days', models.IntegerField()),
                ('number_of_guests', models.IntegerField()),
                ('sub_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.servicechoices')),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
