# Generated by Django 4.2 on 2024-03-01 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_events_delete_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event or Occassion', 'verbose_name_plural': 'Event or Occassion'},
        ),
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
