# Generated by Django 4.2 on 2024-03-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_events_options_events_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodordrinks',
            name='cumulative_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
