# Generated by Django 4.2 on 2024-03-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_foodordrinks_cumulative_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodordrinks',
            name='reserving_guest',
        ),
    ]
