# Generated by Django 4.2 on 2024-03-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0049_alter_booking_check_in_date'),
        ('choices', '0007_additionals'),
        ('restaurant', '0007_remove_foodordrinks_reserving_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_users', models.IntegerField(default=1)),
                ('number_of_times', models.IntegerField(default=1)),
                ('sub_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cumulative_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_service', to='hotel.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.additionals')),
            ],
        ),
    ]
