# Generated by Django 4.2 on 2024-03-08 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0007_additionals'),
        ('restaurant', '0008_otherservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_service', to='choices.additionals'),
        ),
    ]
