# Generated by Django 4.2 on 2024-03-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0007_additionals'),
        ('restaurant', '0009_alter_otherservice_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='choices.servicechoices'),
        ),
    ]
