# Generated by Django 4.2 on 2024-03-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_events_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='number_of_days',
            field=models.IntegerField(default=1),
        ),
    ]
