# Generated by Django 4.2 on 2024-02-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PileUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
    ]
