# Generated by Django 5.0.1 on 2024-01-31 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_mycustomuser_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCustomUser',
        ),
    ]
