# Generated by Django 5.0.1 on 2024-01-31 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
