# Generated by Django 5.0.1 on 2024-02-01 12:55

import django.db.models.deletion
import django.utils.timezone
import management.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_category_room_created_at_room_floor_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('email_adress', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=10, validators=[management.custom_validators.validate_contact])),
                ('nin', models.CharField(blank=True, max_length=14, null=True, validators=[management.custom_validators.validate_nin])),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.BooleanField(default=False, help_text='Tick if there are children among guests.', verbose_name='Children.')),
                ('number_of_guests', models.PositiveBigIntegerField()),
                ('check_in_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('due', 'Due')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mtn', 'Mtn MOMO'), ('airtel', 'Airtel Money'), ('bank', 'Bank transfer')], default='cash', max_length=15)),
                ('booking_source', models.CharField(blank=True, choices=[('online', 'Online'), ('walk_in', 'Walk-in'), ('phone', 'Phone Reservation')], default='walk_in', max_length=15, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special considerations or instructions to hotel staff.', null=True)),
                ('standard_rate', models.BooleanField(default=False, verbose_name='Standard Rate')),
                ('promotional_rate', models.BooleanField(default=False, verbose_name='Promotional Rate')),
                ('corporate_rate', models.BooleanField(default=False, verbose_name='Corporate Rate')),
                ('booking_number', models.CharField(max_length=20, unique=True)),
                ('room_or_rooms', models.ManyToManyField(related_name='bookings', to='hotel.room')),
                ('guest_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_profile', to='hotel.guest')),
            ],
        ),
    ]
