# Generated by Django 5.0.1 on 2024-02-02 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_booking_booking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guest_contact', models.CharField(max_length=15)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_adults', models.PositiveIntegerField(default=1)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit', models.BooleanField(default=False, help_text='Tick if there is any deposit payment', verbose_name='Deposit Paid')),
                ('deposit_amount', models.FloatField(default=0)),
                ('room_or_rooms', models.ManyToManyField(related_name='reservations', to='hotel.room')),
            ],
        ),
    ]
