# Generated by Django 5.0.1 on 2024-02-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_remove_booking_number_of_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cleaned',
            field=models.CharField(default='Not yet', max_length=15),
        ),
    ]
