# Generated by Django 5.0.1 on 2024-02-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_room_cleaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Time for invalidation of reservation contract.', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='active', max_length=11),
        ),
    ]
