# Generated by Django 4.2 on 2024-02-12 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_reservation_deadline_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='corporate_rate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='promotional_rate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='standard_rate',
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('due', 'Due')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mtn', 'Mtn MOMO'), ('airtel', 'Airtel Money'), ('bank', 'Bank transfer')], default='cash', max_length=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('standard_rate', models.BooleanField(default=False, verbose_name='Standard Rate')),
                ('promotional_rate', models.BooleanField(default=False, verbose_name='Promotional Rate')),
                ('corporate_rate', models.BooleanField(default=False, verbose_name='Corporate Rate')),
                ('booking_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='hotel.guest')),
                ('reserve_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_info', to='hotel.reservation')),
            ],
        ),
    ]
