# Generated by Django 4.2 on 2024-02-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_remove_booking_corporate_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Currency: Ugx', max_digits=10),
        ),
    ]
