# Generated by Django 4.2 on 2024-02-13 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_rename_price_room_standard_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='booking_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='hotel.guest'),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='reserve_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_info', to='hotel.reservation'),
        ),
    ]
