# Generated by Django 4.2 on 2024-02-13 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_paymentinformation_booking_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='guest_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_details', to='hotel.guest'),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='booking_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='hotel.booking'),
        ),
    ]
