# Generated by Django 4.2 on 2024-02-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_paymentinformation_guest_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest_profile',
        ),
        migrations.RemoveField(
            model_name='paymentinformation',
            name='guest_details',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
