# Generated by Django 4.2 on 2024-02-13 13:00

from django.db import migrations, models
import django.db.models.deletion
import management.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_remove_booking_guest_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('email_adress', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=10, validators=[management.custom_validators.validate_contact])),
                ('nin', models.CharField(blank=True, max_length=14, null=True, validators=[management.custom_validators.validate_nin])),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('guest_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_profile', to='hotel.booking')),
            ],
        ),
    ]
