# Generated by Django 4.2 on 2024-02-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
