# Generated by Django 4.2 on 2024-02-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_paymentinformation_receipt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_number',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
