# Generated by Django 4.2 on 2024-02-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_reservation_reservation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
