# Generated by Django 4.2 on 2024-02-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_reservation_balance_alter_reservation_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
