# Generated by Django 4.2 on 2024-02-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateTimeField(),
        ),
    ]
