# Generated by Django 4.2 on 2024-02-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.BooleanField(default=False, verbose_name='Guest Has Checked In'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_in',
            field=models.BooleanField(default=False, verbose_name='Guest Has Checked In'),
        ),
    ]
