# Generated by Django 4.2 on 2024-02-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_booking_check_in_reservation_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.BooleanField(default=False, help_text='Tick if guest has checked in', verbose_name='Guest Has Checked In'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.BooleanField(default=False, help_text='Tick if guest has checked in', verbose_name='Guest Has Checked In'),
        ),
    ]
