# Generated by Django 4.2 on 2024-02-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_alter_booking_check_in_alter_reservation_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
