# Generated by Django 4.2 on 2024-02-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_alter_room_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
    ]
