# Generated by Django 4.2 on 2024-02-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_remove_category_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='room_count',
            field=models.PositiveIntegerField(default=0, help_text='number of rooms in this category.'),
        ),
    ]
