# Generated by Django 4.2 on 2024-02-22 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_booking_booking_time_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
