# Generated by Django 4.2 on 2024-02-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0033_alter_reservation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('due', 'Due')], default='paid', max_length=20),
        ),
    ]
