# Generated by Django 4.2 on 2024-02-25 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
        ('hotel', '0035_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.ForeignKey(default='hj', on_delete=django.db.models.deletion.CASCADE, to='choices.reservationstatus'),
        ),
    ]
