# Generated by Django 4.2 on 2024-02-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
        ('hotel', '0037_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='choices.bookingsource'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='choices.bookingstatus'),
        ),
    ]
