# Generated by Django 4.2 on 2024-02-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
        ('hotel', '0038_alter_booking_booking_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='choices.genderchoices'),
        ),
    ]
