# Generated by Django 4.2 on 2024-02-25 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
        ('hotel', '0039_alter_guest_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='choices.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='choices.paymentstatus'),
        ),
    ]
