# Generated by Django 4.2 on 2024-02-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
        ('hotel', '0040_alter_paymentinformation_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_source',
            field=models.ForeignKey(default='----', on_delete=django.db.models.deletion.CASCADE, to='choices.bookingsource'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.ForeignKey(default='----', on_delete=django.db.models.deletion.CASCADE, to='choices.bookingstatus'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='gender',
            field=models.ForeignKey(default='----', on_delete=django.db.models.deletion.CASCADE, to='choices.genderchoices'),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_method',
            field=models.ForeignKey(default='----', on_delete=django.db.models.deletion.CASCADE, to='choices.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_status',
            field=models.ForeignKey(default='----', on_delete=django.db.models.deletion.CASCADE, to='choices.paymentstatus'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.ForeignKey(default='----', on_delete=django.db.models.deletion.CASCADE, to='choices.reservationstatus'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.ForeignKey(default='----', on_delete=django.db.models.deletion.CASCADE, to='choices.roomstatus'),
        ),
    ]
