# Generated by Django 4.2 on 2024-02-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_employpaymentmethod_menuanddrinkschoice_and_more'),
        ('hotel', '0041_alter_booking_booking_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.paymentstatus'),
        ),
    ]
