# Generated by Django 4.2 on 2024-02-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_employpaymentmethod_menuanddrinkschoice_and_more'),
        ('hotel', '0042_alter_paymentinformation_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.bookingsource'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.bookingstatus'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.genderchoices'),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.reservationstatus'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.roomstatus'),
        ),
    ]
