# Generated by Django 4.2 on 2024-03-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0043_alter_booking_booking_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_in',
        ),
    ]
