# Generated by Django 4.2 on 2024-03-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0044_remove_booking_check_in_remove_reservation_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
