# Generated by Django 4.2 on 2024-03-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0045_booking_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
