# Generated by Django 4.2 on 2024-03-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0046_reservation_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='full_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(default=None, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='given_name',
            field=models.CharField(default=None, max_length=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_adults',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
