# Generated by Django 4.2 on 2024-03-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_foodordrinks_reserving_guest'),
        ('hotel', '0047_remove_guest_full_name_guest_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinformation',
            name='reserve_info',
        ),
        migrations.AddField(
            model_name='booking',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
