# Generated by Django 4.2 on 2024-03-05 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0048_remove_paymentinformation_reserve_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
