# Generated by Django 4.2 on 2024-03-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0049_alter_booking_check_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
