# Generated by Django 4.2 on 2024-03-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0050_booking_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
