# Generated by Django 4.2 on 2024-03-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0051_alter_booking_check_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bill_cleared',
            field=models.BooleanField(default=False, help_text='Tick if user has cleared everything before checkout.'),
        ),
    ]
