# Generated by Django 5.0.1 on 2024-02-03 07:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0009_remove_booking_number_of_guests_and_more'),
        ('management', '0024_alter_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='hotel.room')),
            ],
            options={
                'verbose_name': 'Room Maintenance Task',
                'verbose_name_plural': 'Room Maintenance Tasks',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Any important message that the manager or counter need to know.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'group__name': 'Cleaners'}, on_delete=django.db.models.deletion.CASCADE, to='management.customgroup')),
                ('housekeeping_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='house_keeping.housekeepingtask')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_maintenance_requests', to='hotel.room')),
            ],
        ),
    ]
