# Generated by Django 5.0.1 on 2024-02-03 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_remove_booking_number_of_guests_and_more'),
        ('house_keeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='housekeeping_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_request', to='house_keeping.housekeepingtask'),
        ),
        migrations.CreateModel(
            name='CleanRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_cleaned', models.DateTimeField(blank=True, null=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clean_room', to='hotel.room')),
            ],
            options={
                'verbose_name': 'Clean Room',
                'verbose_name_plural': 'Clean Rooms',
            },
        ),
    ]
