# Generated by Django 5.0.1 on 2024-02-03 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_keeping', '0002_alter_maintenancerequest_housekeeping_task_cleanroom'),
        ('management', '0024_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'user__profile__given_name': 'Cleaners'}, on_delete=django.db.models.deletion.CASCADE, to='management.baseuserprofile'),
        ),
    ]
