# Generated by Django 5.0.1 on 2024-02-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_keeping', '0003_alter_maintenancerequest_assigned_to'),
        ('management', '0024_alter_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='housekeeping_tasks', to='management.baseuserprofile'),
        ),
    ]
