# Generated by Django 5.0.1 on 2024-02-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_keeping', '0004_remove_maintenancerequest_assigned_to_and_more'),
        ('management', '0024_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='housekeeping_tasks', to='management.baseuserprofile'),
        ),
    ]
