# Generated by Django 5.0.1 on 2024-02-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_keeping', '0005_maintenancerequest_in_progress_and_more'),
        ('management', '0024_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='housekeeping_tasks', to='management.baseuserprofile'),
        ),
    ]
