# Generated by Django 5.0.1 on 2024-02-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_keeping', '0006_alter_maintenancerequest_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='room',
        ),
    ]
