# Generated by Django 5.0.1 on 2024-02-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_keeping', '0009_initial'),
        ('management', '0024_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='maintenance_tasks', to='management.baseuserprofile'),
        ),
    ]
