# Generated by Django 5.0.1 on 2024-02-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_keeping', '0010_alter_maintenancerequest_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housekeepingtask',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='housekeeping_task',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='CleanRoom',
        ),
        migrations.DeleteModel(
            name='HousekeepingTask',
        ),
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
