# Generated by Django 5.0.1 on 2024-02-08 03:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0009_remove_booking_number_of_guests_and_more'),
        ('house_keeping', '0011_remove_housekeepingtask_room_number_and_more'),
        ('management', '0024_alter_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_cleaned', models.DateTimeField(blank=True, null=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clean_room', to='hotel.room')),
            ],
            options={
                'verbose_name': 'Clean Room',
                'verbose_name_plural': 'Clean Rooms',
            },
        ),
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='hotel.room')),
            ],
            options={
                'verbose_name': 'Room Maintenance Task',
                'verbose_name_plural': 'Room Maintenance Tasks',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Any important message that the manager or counter need to know.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='maintenance_tasks', to='management.baseuserprofile')),
                ('housekeeping_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_request', to='house_keeping.housekeepingtask')),
            ],
            options={
                'verbose_name': 'Maintenance Update',
                'verbose_name_plural': 'Maintenance Updates',
            },
        ),
    ]
