# Generated by Django 4.2 on 2024-02-23 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house_keeping', '0012_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeepingtask',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
