# Generated by Django 4.2 on 2024-02-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Salary Payment Channel',
                'verbose_name_plural': 'Salary Payment Channels',
            },
        ),
        migrations.CreateModel(
            name='MenuAndDrinksChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_or_drink', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Food or Drink Choice',
                'verbose_name_plural': 'Food or Drinks Choices',
            },
        ),
        migrations.AlterModelOptions(
            name='bookingsource',
            options={'verbose_name': 'Booking Channel', 'verbose_name_plural': 'Booking Channels'},
        ),
        migrations.AlterModelOptions(
            name='bookingstatus',
            options={'verbose_name': 'Booking Status', 'verbose_name_plural': 'Booking Status'},
        ),
        migrations.AlterModelOptions(
            name='employmentstatus',
            options={'verbose_name': 'Employment Status', 'verbose_name_plural': 'Employment Status'},
        ),
        migrations.AlterModelOptions(
            name='genderchoices',
            options={'verbose_name': 'Gender Choice', 'verbose_name_plural': 'Gender Choices'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'verbose_name': 'Payment Status', 'verbose_name_plural': 'Payment Status'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Individual Position', 'verbose_name_plural': 'Individual Positions'},
        ),
        migrations.AlterModelOptions(
            name='reservationstatus',
            options={'verbose_name': 'Reservation Status', 'verbose_name_plural': 'Reservation Status'},
        ),
        migrations.AlterModelOptions(
            name='roomstatus',
            options={'verbose_name': 'Room Status', 'verbose_name_plural': 'Room Status'},
        ),
    ]
