# Generated by Django 4.2 on 2024-02-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_employpaymentmethod_menuanddrinkschoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Extra Service',
                'verbose_name_plural': 'Extra Services',
            },
        ),
        migrations.RenameField(
            model_name='menuanddrinkschoice',
            old_name='food_or_drink',
            new_name='name',
        ),
        migrations.AddField(
            model_name='menuanddrinkschoice',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='menuanddrinkschoice',
            name='units',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
