# Generated by Django 4.2 on 2024-02-29 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0003_servicechoices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicechoices',
            options={'verbose_name': 'Event Choices', 'verbose_name_plural': 'Event Choices'},
        ),
        migrations.RenameField(
            model_name='servicechoices',
            old_name='name',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='servicechoices',
            old_name='price',
            new_name='price_per_day',
        ),
        migrations.AddField(
            model_name='servicechoices',
            name='event_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicechoices',
            name='reservation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
