# Generated by Django 4.2 on 2024-03-01 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0004_alter_servicechoices_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicechoices',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='servicechoices',
            name='reservation_date',
        ),
    ]
