# Generated by Django 4.2 on 2024-03-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0048_remove_paymentinformation_reserve_info_and_more'),
        ('choices', '0005_remove_servicechoices_event_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationStatus',
        ),
    ]
