# Generated by Django 4.2 on 2024-03-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGuestStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(unique=True)),
                ('total_guests', models.IntegerField(default=0)),
                ('male_guests', models.IntegerField(default=0)),
                ('female_guests', models.IntegerField(default=0)),
            ],
        ),
    ]
