# Generated by Django 4.2 on 2024-03-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darsh_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBookingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('num_bookings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyGuestStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('num_guests', models.IntegerField(default=0)),
            ],
        ),
    ]
